### ISSUE TITLE
Badly converted XMs

### ISSUE THREAD

**Issue by Knurek-NC** [MCJack123/UnkrawerterGBA#2] opened 2020-10-16 16:37 UTC
A bunch of games isn't getting converted properly:

Pixeline i Pixieland
Postman Pat and the Greendale Rocket
Zoey 101 (the single .xm file)
Cocoto - Kart Racer (broken samples)
Cocoto - Platform Jumper (broken samples)
Bratz - Forever Diamondz (broken samples)

I've attached screenshots of how they look in XMPlay, it looks like the instrument list isn't converted properly.
![2020-10-16_18-35-51](https://user-images.githubusercontent.com/22718168/96284854-78df7980-0fde-11eb-8811-d7e447120a6a.png)
![2020-10-16_18-36-02](https://user-images.githubusercontent.com/22718168/96284857-79781000-0fde-11eb-8448-d51f126db3b4.png)

I've tried converting these games with earlier versions of the tool, with the same results.

**Comment by MCJack123** [comment] 2020-10-16 16:50
This issue will be fixed in 3.1. ~~The problem was caused by an incorrect guess as to what the `hq` field meant in samples - I thought it meant 16-bit samples are present, but it actually tells Krawall to apply interpolation (with 8-bit samples).~~

That was a different bug. Actually, this is caused by some bytes being flipped in the part of the instrument data that says which samples are used for certain instruments. These bytes would end up telling UnkrawerterGBA to look for a sample that is way out of bounds, which caused it to just skip the sample. Because of that, the XM would be filled with incomplete data, and the module ended up being corrupted.

Now, UnkrawerterGBA checks to see if the byte is flipped, and if it is it ignores that byte only, allowing the sample data to stay sane. In addition, if a sample number that is specified is not available, it will no longer fail silently, instead saying that the module is likely corrupted.

**Closed as completed** 2020-10-18 14:35 UTC
